### ISSUE TITLE
Issue with Integration with React Native Project.

### ISSUE THREAD

**Issue by danZheng1993** [onfido/onfido-ios-sdk#17]
I have integrated Onfido iOS SDK to my React Native Project.
But I have ran into some problems.

I get ```Fatal error: Unexpectedly found nil while unwrapping an Optional value```

The Screen to taking photo of id card is shown, but it shows black screen with rectangle and camera button.
Just like when you cover your phone's camera.

I need your help on this issue asap.

Thanks
Really appreciate your help on this.

**Comment by danZheng1993** [comment]
I have fixed this issue and I could pass the document capturing steps.
But after take picture of your self and then I get this kind of error on iOS console.

Please check below files for the reference:



![screen shot 2017-12-23 at 3 23 52](https://user-images.githubusercontent.com/33262634/34310219-2c564ae4-e791-11e7-803d-932d2c0f76e2.png)

**Comment by danZheng1993** [comment]
[Archive 2.zip](https://github.com/onfido/onfido-ios-sdk/files/1583336/Archive.2.zip)

**Comment by anuragajwani** [comment]
@danZheng1993 I am not really experienced with React Native but usually that error will rise when the `OnfidoFlow` instance is deallocated during the flow execution. I am unsure how you would achieve that on the example that you have provided me, at least not until I get some more time on React Native.

If I would have to take an educated guess I would look into making sure the OnfidoManager object is kept in memory during the execution of the flow. The only mentions that I could find to OnfidoManager in `index.js` is in the `componentDidMount` function. I am not sure whether the instance of `OnfidoManager` is kept after the execution of such function.

**Comment by danZheng1993** [comment]
Thanks for your help.
I will send you the update once, I try this solution.

Regards,

**Comment by danZheng1993** [comment]
I still get error with RN integration.
Please check the attached image to see the error log on Xcode.
![screen shot 2018-01-05 at 3 22 23](https://user-images.githubusercontent.com/33262634/34580438-fa8a0406-f1c7-11e7-89cc-9b8bba628289.png)
Really appreciate your help.

Regards,
Daniel.

**Comment by DVSoftware** [comment]
We are also experiencing this issue

**Comment by anuragajwani** [comment]
@danZheng1993 @DVSoftware we will look into React Native integration

**Comment by danZheng1993** [comment]
Thanks, @anuragajwani 
Currently, I have integrated the Onfido using React-Native-Camera and Web API.
It would be great if Onfido SDK is integrated with RN.

**Comment by anuragajwani** [comment]
@danZheng1993 @DVSoftware there are two tasks currently being reviewed to ease the integration with React Native. We are improving the objective-c interface as well as memory management. I will update this issue once we have any further updates.

**Comment by danZheng1993** [comment]
Thanks, @anuragajwani 

Really appreciate your help.

**Comment by anuragajwani** [comment]
@danZheng1993 @DVSoftware we have just released a new version of the Onfido iOS SDK (5.3.0) which includes an improved objective-c interface which should ease in exposing the native code to React Native as I understand from the React Native [instructions](https://facebook.github.io/react-native/docs/native-modules-ios.html). We will continue to work on improving the memory management.

I hope this helps,
Anurag Ajwani

**Comment by anuragajwani** [comment]
Hello @danZheng1993 & @DVSoftware,

I have added an example on how to integrate the Onfido iOS SDK with React Native https://github.com/onfido/onfido-sdk-react-native-sample-app/pull/3. I have also answered to a similar issue [here](https://github.com/onfido/onfido-sdk-react-native-sample-app/issues/1).

Please let me know if you are still encountering issues integrating with the Onfido iOS SDK,
Anurag

**Comment by martynasadomaitis** [comment]
Hello @anuragajwani . Unfortunately, I still get the same exact error with with iOS Onfido SDK 6.0.0 using React Native 0.55.4 . I do not get it every time, but mostly at the times when I open Onfido view and then go back from it quite quickly. On iPhone 5 I get this error very often, but on iPhone X - very rarely.

I tried various things to the extent where I tried to put ONFlow object reference to global variable so that it would not get released from memory no matter what. However, it seems to have no effect.
