### ISSUE TITLE
Bad translation in Localizable_DE.strings

### ISSUE THREAD

**Issue by bienemann** [onfido/onfido-ios-sdk#202]
### What was the expected behaviour?

`onfido_doc_capture_header_license_back` key should tell the user to capture the back of his driver's license with the sentence `Rückseite der Führerschein`, like it happens in the other document capture keys such as:

```
"onfido_doc_capture_header_id_back" = "Rückseite der Karte";
"onfido_doc_capture_header_permit_back" = "Rückseite der Erlaubnis";
```

### What happened instead?

It does not specify that the back of the license is required:

```
"onfido_doc_capture_header_license_back" = "Führerschein";
```

### Version info:

- Cocoapods (if applicable): Not applicable
- Onfido SDK (Debug/Release): 18.10.1
- iOS: 14.2
- Xcode: 12.2
- Device/Simulator: Not applicable
- Device/Simulator language: German

### Integration configuration:

Not relevant.

### Steps to reproduce:

- Open the Onfido flow configured for driver's license validation on a device/simulator configured in the German language.
- Navigate to the document back capture screen.

**Comment by anuragajwani** [comment]
Hi @bienemann 

Thank you for raising the issue. I have create a ticket for this and will update once I have a response back from the team.

Anurag

**Comment by keremgund** [comment]
Hello,
We've fixed the issue and it will be part of the next release. 
I will let you know once the release is done.

Thanks,
Kerem

**Comment by anuragajwani** [comment]
Hi @bienemann 

We have fixed the issue in 20.0.0. Please let us know if you still encounter issues.

Sorry for the inconvenience,
Anurag

**Comment by davidgdoll** [comment]
Hi @anuragajwani and @keremgund I think the issue still exists in the latest versions, the _onfido_doc_capture_header_license_back_ key still has the value = **Führerschein** and not **Rückseite der Führerschein** or something similar.
