### ISSUE TITLE
NSInternalInconsistencyException on -[AVAssetWriterInput appendSampleBuffer:]

### ISSUE THREAD

**Issue by lmmenge** [onfido/onfido-ios-sdk#220]
### What was the expected behaviour?

The Onfido library shouldn't crash.

### What happened instead?

It crashed with the following exception:
```
NSInternalInconsistencyException
*** -[AVAssetWriterInput appendSampleBuffer:] Cannot append sample buffer: Must start a session (using -[AVAssetWriter startSessionAtSourceTime:) first
```

And the following crash log:
```
OS Version: iOS 14.4 (18D52)
Report Version: 104

Exception Type: EXC_CRASH (SIGABRT)
Crashed Thread: 12

Application Specific Information:
*** -[AVAssetWriterInput appendSampleBuffer:] Cannot append sample buffer: Must start a session (using -[AVAssetWriter startSessionAtSourceTime:) first

Thread 12 Crashed:
0   CoreFoundation                  0x32e10a9d8         <redacted>
1   libobjc.A.dylib                 0x347e73b54         objc_exception_throw
2   AVFCore                         0x36980c7bc         <redacted>
3   Onfido                          0x105c596bc         __swift_memcpy17_8
4   Onfido                          0x105c3384c         globalinit_33_6415B0A579C15A74E4EFB0C40ADAB8DD_func3
5   Foundation                      0x31af232e8         <redacted>
6   Foundation                      0x31ae20098         <redacted>
7   Foundation                      0x31af255a0         <redacted>
8   Foundation                      0x31ae1fd54         <redacted>
9   Foundation                      0x31af25f98         <redacted>
10  Foundation                      0x31af25a64         <redacted>
11  libdispatch.dylib               0x19950575c         <redacted>
12  libdispatch.dylib               0x199556280         <redacted>
13  libdispatch.dylib               0x1994fb390         <redacted>
14  libdispatch.dylib               0x1994faad4         <redacted>
15  libdispatch.dylib               0x199507f3c         <redacted>
16  libdispatch.dylib               0x199508704         <redacted>
17  libsystem_pthread.dylib         0x38bfd8568         _pthread_wqthread
18  libsystem_pthread.dylib         0x38bfdb874         start_wqthread

Thread 0
0   libsystem_kernel.dylib          0x3757ab644         mach_msg_trap
1   libsystem_kernel.dylib          0x3757aaa48         mach_msg
2   CoreFoundation                  0x32e08a0fc         <redacted>
3   CoreFoundation                  0x32e084570         <redacted>
4   CoreFoundation                  0x32e083ba0         CFRunLoopRunSpecific
5   GraphicsServices                0x367877598         GSEventRunModal
6   UIKitCore                       0x324d472f4         <redacted>
7   UIKitCore                       0x324d4c874         UIApplicationMain
8   bunq                            0x204b46c30         main (main.m:17)
9   libdyld.dylib                   0x33c7ff568         <redacted>

Thread 1 name: com.apple.uikit.eventfetch-thread
0   libsystem_kernel.dylib          0x3757ab644         mach_msg_trap
1   libsystem_kernel.dylib          0x3757aaa48         mach_msg
2   CoreFoundation                  0x32e08a0fc         <redacted>
3   CoreFoundation                  0x32e084570         <redacted>
4   CoreFoundation                  0x32e083ba0         CFRunLoopRunSpecific
5   Foundation                      0x31ae097f8         <redacted>
6   Foundation                      0x31ae096d8         <redacted>
7   UIKitCore                       0x324df3054         <redacted>
8   Foundation                      0x31af664bc         <redacted>
9   libsystem_pthread.dylib         0x38bfd6c9c         _pthread_start

Thread 2
0   libsystem_kernel.dylib          0x3757cebf0         __semwait_signal
1   libsystem_c.dylib               0x36aff06d4         nanosleep
2   libsystem_c.dylib               0x36aff04d4         sleep
3   Sentry                          0x2b805a9b8         monitorCachedData
4   libsystem_pthread.dylib         0x38bfd6c9c         _pthread_start

Thread 3 name: SentryCrash Exception Handler (Secondary)
0   libsystem_kernel.dylib          0x3757ab644         mach_msg_trap
1   libsystem_kernel.dylib          0x3757aaa48         mach_msg
2   libsystem_kernel.dylib          0x3757c851c         thread_suspend
3   Sentry                          0x2b805167c         handleExceptions
4   libsystem_pthread.dylib         0x38bfd6c9c         _pthread_start

Thread 4 name: SentryCrash Exception Handler (Primary)
0   libsystem_kernel.dylib          0x3757ab644         mach_msg_trap
1   libsystem_kernel.dylib          0x3757aaa48         mach_msg
2   Sentry                          0x2b80516a8         handleExceptions
3   libsystem_pthread.dylib         0x38bfd6c9c         _pthread_start

Thread 5 name: com.apple.NSURLConnectionLoader
0   libsystem_kernel.dylib          0x3757ab644         mach_msg_trap
1   libsystem_kernel.dylib          0x3757aaa48         mach_msg
2   CoreFoundation                  0x32e08a0fc         <redacted>
3   CoreFoundation                  0x32e084570         <redacted>
4   CoreFoundation                  0x32e083ba0         CFRunLoopRunSpecific
5   CFNetwork                       0x31ab6e4b0         _CFURLStorageSessionCopyCache
6   Foundation                      0x31af664bc         <redacted>
7   libsystem_pthread.dylib         0x38bfd6c9c         _pthread_start

Thread 6 name: AVAudioSession Notify Thread
0   libsystem_kernel.dylib          0x3757ab644         mach_msg_trap
1   libsystem_kernel.dylib          0x3757aaa48         mach_msg
2   CoreFoundation                  0x32e08a0fc         <redacted>
3   CoreFoundation                  0x32e084570         <redacted>
4   CoreFoundation                  0x32e083ba0         CFRunLoopRunSpecific
5   AudioSession                    0x339bd7098         <redacted>
6   AudioSession                    0x339bd8ff8         <redacted>
7   libsystem_pthread.dylib         0x38bfd6c9c         _pthread_start

Thread 7 name: com.apple.CoreMotion.MotionThread
0   libsystem_kernel.dylib          0x3757ab644         mach_msg_trap
1   libsystem_kernel.dylib          0x3757aaa48         mach_msg
2   CoreFoundation                  0x32e08a0fc         <redacted>
3   CoreFoundation                  0x32e084570         <redacted>
4   CoreFoundation                  0x32e083ba0         CFRunLoopRunSpecific
5   CoreFoundation                  0x32e084c60         CFRunLoopRun
6   CoreMotion                      0x338b73d68         CLClientCreateIso6709Notation
7   libsystem_pthread.dylib         0x38bfd6c9c         _pthread_start

Thread 8
0   libsystem_kernel.dylib          0x3757cf48c         __workq_kernreturn
1   libsystem_pthread.dylib         0x38bfd85f0         _pthread_wqthread

Thread 9
0   libsystem_kernel.dylib          0x3757cf48c         __workq_kernreturn
1   libsystem_pthread.dylib         0x38bfd85f0         _pthread_wqthread

Thread 10
0   libsystem_kernel.dylib          0x3757cf48c         __workq_kernreturn
1   libsystem_pthread.dylib         0x38bfd85f0         _pthread_wqthread

Thread 11
0   libsystem_pthread.dylib         0x38bfdb86c         <redacted>

Thread 12 Crashed:
0   CoreFoundation                  0x32e10a9d8         <redacted>
1   libobjc.A.dylib                 0x347e73b54         objc_exception_throw
2   AVFCore                         0x36980c7bc         <redacted>
3   Onfido                          0x105c596bc         __swift_memcpy17_8
4   Onfido                          0x105c3384c         globalinit_33_6415B0A579C15A74E4EFB0C40ADAB8DD_func3
5   Foundation                      0x31af232e8         <redacted>
6   Foundation                      0x31ae20098         <redacted>
7   Foundation                      0x31af255a0         <redacted>
8   Foundation                      0x31ae1fd54         <redacted>
9   Foundation                      0x31af25f98         <redacted>
10  Foundation                      0x31af25a64         <redacted>
11  libdispatch.dylib               0x19950575c         <redacted>
12  libdispatch.dylib               0x199556280         <redacted>
13  libdispatch.dylib               0x1994fb390         <redacted>
14  libdispatch.dylib               0x1994faad4         <redacted>
15  libdispatch.dylib               0x199507f3c         <redacted>
16  libdispatch.dylib               0x199508704         <redacted>
17  libsystem_pthread.dylib         0x38bfd8568         _pthread_wqthread
18  libsystem_pthread.dylib         0x38bfdb874         start_wqthread

Thread 13
0   libsystem_pthread.dylib         0x38bfdb86c         <redacted>



EOF
```

### Version info:

- Cocoapods (if applicable): N/A
- Onfido SDK (Debug/Release): 20.0.1 (Release)
- iOS: 14.4 / 14.3 / 14.0.1 / 12.5.1 /  11.3.1
- Xcode: 12.4
- Device/Simulator: iPhone 7 Plus / iPhone 7 / iPhone SE / iPhone 5s / iPhone 6
- Device/Simulator language: Unknown

### Integration configuration:

The only change we're doing out of the ordinary is using a custom `strings` file:
```
[configBuilder withCustomLocalizationWithTableName:@"Onfido"];
```

### Steps to reproduce:

Couldn't reproduce internally. This is a crash out from one of our users.

**Comment by anuragajwani** [comment]
Hi @lmmenge,

Sorry to hear that your customer experienced a crash. We will investigate the issue. If you do get more crashes please let us know.

Sorry for the inconvenience caused,
Anurag

**Comment by igled7** [comment]
We are having the same crash.

**Comment by keremgund** [comment]
Hi @lmmenge ,
Although we can't reproduce on our side, we've spotted some "potential" logic that could cause this problem.
We're working on it now and I will let you know once we release it.

Thanks,
Kerem

**Comment by keremgund** [comment]
Hi @lmmenge ,
We've developed fix to prevent this problem. It will be delivered within next release. 
Once release done I will let you know.

Kerem

**Comment by anuragajwani** [comment]
Hi @lmmenge

We have now released the defensive code to prevent this scenario from occurring in [21.2.0](https://github.com/onfido/onfido-ios-sdk/blob/master/CHANGELOG.md#2120---2021-03-29).

Please let us know if you get more reports of this issue using the latest code.

**Comment by lmmenge** [comment]
@anuragajwani Thanks! Will integrate the new release and let you know in a couple of weeks.

**Comment by lmmenge** [comment]
@anuragajwani it seems this still happens. Though it has only happened twice for one user since integrating Onfido 21.2.0:

```
OS Version: iOS 14.4 (18D52)
Report Version: 104

Exception Type: EXC_CRASH (SIGABRT)
Crashed Thread: 13

Application Specific Information:
*** -[AVAssetWriterInput appendSampleBuffer:] Cannot append sample buffer: Must start a session (using -[AVAssetWriter startSessionAtSourceTime:) first

Thread 13 Crashed:
0   CoreFoundation                  0x3189989d8         <redacted>
1   libobjc.A.dylib                 0x3411b8b54         objc_exception_throw
2   AVFCore                         0x32753d7bc         <redacted>
3   Onfido                          0x1029b3158         __swift_memcpy17_8
4   Onfido                          0x10298be68         block_destroy_helper.6
5   Foundation                      0x31aef72e8         <redacted>
6   Foundation                      0x31adf4098         <redacted>
7   Foundation                      0x31aef95a0         <redacted>
8   Foundation                      0x31adf3d54         <redacted>
9   Foundation                      0x31aef9f98         <redacted>
10  Foundation                      0x31aef9a64         <redacted>
11  libdispatch.dylib               0x31827275c         <redacted>
12  libdispatch.dylib               0x3182c3280         <redacted>
13  libdispatch.dylib               0x318268390         <redacted>
14  libdispatch.dylib               0x318267ad4         <redacted>
15  libdispatch.dylib               0x318274f3c         <redacted>
16  libdispatch.dylib               0x318275704         <redacted>
17  libsystem_pthread.dylib         0x3a9af0568         _pthread_wqthread
18  libsystem_pthread.dylib         0x3a9af3874         start_wqthread

Thread 0
0   libsystem_kernel.dylib          0x3708e6644         mach_msg_trap
1   libsystem_kernel.dylib          0x3708e5a48         mach_msg
2   CoreFoundation                  0x3189180fc         <redacted>
3   CoreFoundation                  0x318912570         <redacted>
4   CoreFoundation                  0x318911ba0         CFRunLoopRunSpecific
5   GraphicsServices                0x346473598         GSEventRunModal
6   UIKitCore                       0x31d05a2f4         <redacted>
7   UIKitCore                       0x31d05f874         UIApplicationMain
8   bunq                            0x2014d54ac         main (main.m:17)
9   libdyld.dylib                   0x318361568         <redacted>

Thread 1 name: com.apple.uikit.eventfetch-thread
0   libsystem_kernel.dylib          0x3708e6644         mach_msg_trap
1   libsystem_kernel.dylib          0x3708e5a48         mach_msg
2   CoreFoundation                  0x3189180fc         <redacted>
3   CoreFoundation                  0x318912570         <redacted>
4   CoreFoundation                  0x318911ba0         CFRunLoopRunSpecific
5   Foundation                      0x31addd7f8         <redacted>
6   Foundation                      0x31addd6d8         <redacted>
7   UIKitCore                       0x31d106054         <redacted>
8   Foundation                      0x31af3a4bc         <redacted>
9   libsystem_pthread.dylib         0x3a9aeec9c         _pthread_start

Thread 2
0   libsystem_kernel.dylib          0x370909bf0         __semwait_signal
1   libsystem_c.dylib               0x32a4326d4         nanosleep
2   libsystem_c.dylib               0x32a4324d4         sleep
3   Sentry                          0x1023ab9b8         monitorCachedData
4   libsystem_pthread.dylib         0x3a9aeec9c         _pthread_start

Thread 3 name: SentryCrash Exception Handler (Secondary)
0   libsystem_kernel.dylib          0x3708e6644         mach_msg_trap
1   libsystem_kernel.dylib          0x3708e5a48         mach_msg
2   libsystem_kernel.dylib          0x37090351c         thread_suspend
3   Sentry                          0x1023a267c         handleExceptions
4   libsystem_pthread.dylib         0x3a9aeec9c         _pthread_start

Thread 4 name: SentryCrash Exception Handler (Primary)
0   libsystem_kernel.dylib          0x3708e6644         mach_msg_trap
1   libsystem_kernel.dylib          0x3708e5a48         mach_msg
2   Sentry                          0x1023a26a8         handleExceptions
3   libsystem_pthread.dylib         0x3a9aeec9c         _pthread_start

Thread 5 name: com.apple.NSURLConnectionLoader
0   libsystem_kernel.dylib          0x3708e6644         mach_msg_trap
1   libsystem_kernel.dylib          0x3708e5a48         mach_msg
2   CoreFoundation                  0x3189180fc         <redacted>
3   CoreFoundation                  0x318912570         <redacted>
4   CoreFoundation                  0x318911ba0         CFRunLoopRunSpecific
5   CFNetwork                       0x3198964b0         _CFURLStorageSessionCopyCache
6   Foundation                      0x31af3a4bc         <redacted>
7   libsystem_pthread.dylib         0x3a9aeec9c         _pthread_start

Thread 6 name: AVAudioSession Notify Thread
0   libsystem_kernel.dylib          0x3708e6644         mach_msg_trap
1   libsystem_kernel.dylib          0x3708e5a48         mach_msg
2   CoreFoundation                  0x3189180fc         <redacted>
3   CoreFoundation                  0x318912570         <redacted>
4   CoreFoundation                  0x318911ba0         CFRunLoopRunSpecific
5   AudioSession                    0x32749a098         <redacted>
6   AudioSession                    0x32749bff8         <redacted>
7   libsystem_pthread.dylib         0x3a9aeec9c         _pthread_start

Thread 7 name: JavaScriptCore bmalloc scavenger
0   libsystem_kernel.dylib          0x37090961c         __psynch_cvwait
1   libsystem_pthread.dylib         0x3a9ae845c         <redacted>
2   libc++.1.dylib                  0x3412eae0c         std::__1::condition_variable::wait
3   JavaScriptCore                  0x32b37fd54         <redacted>
4   JavaScriptCore                  0x32b384784         <redacted>
5   JavaScriptCore                  0x32b384198         <redacted>
6   JavaScriptCore                  0x32b3858c0         <redacted>
7   libsystem_pthread.dylib         0x3a9aeec9c         _pthread_start

Thread 8
0   libsystem_pthread.dylib         0x3a9af386c         <redacted>

Thread 9
0   libsystem_kernel.dylib          0x37090a48c         __workq_kernreturn
1   libsystem_pthread.dylib         0x3a9af05f0         _pthread_wqthread

Thread 10
0   libsystem_pthread.dylib         0x3a9af386c         <redacted>

Thread 11
0   libsystem_kernel.dylib          0x37090a48c         __workq_kernreturn
1   libsystem_pthread.dylib         0x3a9af05f0         _pthread_wqthread

Thread 12
0   libsystem_pthread.dylib         0x3a9af386c         <redacted>

Thread 13 Crashed:
0   CoreFoundation                  0x3189989d8         <redacted>
1   libobjc.A.dylib                 0x3411b8b54         objc_exception_throw
2   AVFCore                         0x32753d7bc         <redacted>
3   Onfido                          0x1029b3158         __swift_memcpy17_8
4   Onfido                          0x10298be68         block_destroy_helper.6
5   Foundation                      0x31aef72e8         <redacted>
6   Foundation                      0x31adf4098         <redacted>
7   Foundation                      0x31aef95a0         <redacted>
8   Foundation                      0x31adf3d54         <redacted>
9   Foundation                      0x31aef9f98         <redacted>
10  Foundation                      0x31aef9a64         <redacted>
11  libdispatch.dylib               0x31827275c         <redacted>
12  libdispatch.dylib               0x3182c3280         <redacted>
13  libdispatch.dylib               0x318268390         <redacted>
14  libdispatch.dylib               0x318267ad4         <redacted>
15  libdispatch.dylib               0x318274f3c         <redacted>
16  libdispatch.dylib               0x318275704         <redacted>
17  libsystem_pthread.dylib         0x3a9af0568         _pthread_wqthread
18  libsystem_pthread.dylib         0x3a9af3874         start_wqthread

Thread 14
0   libsystem_pthread.dylib         0x3a9af386c         <redacted>

Thread 15
0   libsystem_pthread.dylib         0x3a9af386c         <redacted>



EOF
```

**Comment by keremgund** [comment]
Hi @lmmenge ,
Thanks for letting us know about the result. We will be making further investigation to understand what else can cause this crash. I will share an update here whenever we made progress on the investigation.

Thanks,
Kerem

**Comment by lmmenge** [comment]
@keremgund We still get a crash here from time to time.

We recently have done some work involving `AVAssetWriter` and ran into this in our own code too. The solution for us was to make sure we only wrote to the Input from a single queue. AVFoundation would often call our callbacks with new samples in different queues.

**Comment by AndreasVerhoeven** [comment]
@keremgund any input on this? This still happens quite often...

**Comment by canhth** [comment]
Hi @keremgund,
I'm still getting this crash for a long time, affecting >2500 users. Hope the team can help us to solve this 🙇‍♂️ 

```

Fatal Exception: NSInternalInconsistencyException
0  CoreFoundation                 0x11b928 __exceptionPreprocess
1  libobjc.A.dylib                0x26480 objc_exception_throw
2  AVFCore                        0x86178 __41-[AVAssetWriterInput appendSampleBuffer:]_block_invoke
3  Onfido                         0x97de0 (Missing UUID 0d7790d2a7923901998faa62d5761fdd)
4  Onfido                         0x1d6c0 (Missing UUID 0d7790d2a7923901998faa62d5761fdd)
5  Foundation                     0x121b2c __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__
6  Foundation                     0x1e6d8 -[NSBlockOperation main]
7  Foundation                     0x123dc8 __NSOPERATION_IS_INVOKING_MAIN__
8  Foundation                     0x1e394 -[NSOperation start]
9  Foundation                     0x1247c0 __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__
10 Foundation                     0x12428c __NSOQSchedule_f
11 libdispatch.dylib              0x103e4 _dispatch_block_async_invoke2
12 libdispatch.dylib              0x61298 _dispatch_client_callout
13 libdispatch.dylib              0x6028 _dispatch_continuation_pop$VARIANT$mp
14 libdispatch.dylib              0x576c _dispatch_async_redirect_invoke
15 libdispatch.dylib              0x12bb8 _dispatch_root_queue_drain
16 libdispatch.dylib              0x13378 _dispatch_worker_thread2
17 libsystem_pthread.dylib        0xb580 _pthread_wqthread
18 libsystem_pthread.dylib        0xe86c start_wqthread

com.apple.main-thread
0  libsystem_kernel.dylib         0x3908 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x2d0c mach_msg + 72
2  CoreFoundation                 0x9a4b8 __CFRunLoopServiceMachPort + 368
3  CoreFoundation                 0x948b8 __CFRunLoopRun + 1184
4  CoreFoundation                 0x93ed0 CFRunLoopRunSpecific + 572
5  GraphicsServices               0x3570 GSEventRunModal + 160
6  UIKitCore                      0xb302d0 -[UIApplication _run] + 1052
7  UIKitCore                      0xb3584c UIApplicationMain + 164
8  Binance                        0x44dc main + 4300899548 (<compiler-generated>:4300899548)
9  libdyld.dylib                  0x1140 start + 4

Thread
0  libsystem_kernel.dylib         0x27580 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x3308 _pthread_cond_wait$VARIANT$mp + 1236
2  libc++.1.dylib                 0xcab8 std::__1::condition_variable::__do_timed_wait(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >) + 96
3  Abacus                         0x14c588 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, kotlin::RepeatedTimer::RepeatedTimer<long long, std::__1::ratio<1l, 1000000l>, (anonymous namespace)::GCSchedulerDataWithTimer::GCSchedulerDataWithTimer(kotlin::gc::GCSchedulerConfig&, std::__1::function<void ()>)::'lambda'()>(std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l> >, (anonymous namespace)::GCSchedulerDataWithTimer::GCSchedulerDataWithTimer(kotlin::gc::GCSchedulerConfig&, std::__1::function<void ()>)::'lambda'())::'lambda'()> >(void*) + 164
4  libsystem_pthread.dylib        0x9c74 _pthread_start + 288
5  libsystem_pthread.dylib        0xe878 thread_start + 8

```

**Comment by zvjerka24** [comment]
I'm also getting this crash:

```
Fatal Exception: NSInternalInconsistencyException
*** -[AVAssetWriterInput appendSampleBuffer:] Cannot append sample buffer: Must start a session (using -[AVAssetWriter startSessionAtSourceTime:) first

Fatal Exception: NSInternalInconsistencyException
0  CoreFoundation                 0x9e38 __exceptionPreprocess
1  libobjc.A.dylib                0x178d8 objc_exception_throw
2  AVFCore                        0xae804 __41-[AVAssetWriterInput appendSampleBuffer:]_block_invoke
3  Onfido                         0xa1cc4 (Missing UUID 2c72ea826111380fba68b72392b8e697)
4  Onfido                         0x1b774 (Missing UUID 2c72ea826111380fba68b72392b8e697)
5  Foundation                     0xa7060 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__
6  Foundation                     0x7b1b0 -[NSBlockOperation main]
7  Foundation                     0x7b140 __NSOPERATION_IS_INVOKING_MAIN__
8  Foundation                     0x3c4f4 -[NSOperation start]
9  Foundation                     0x3c228 __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__
10 Foundation                     0x41940 __NSOQSchedule_f
11 libdispatch.dylib              0x13114 _dispatch_block_async_invoke2
12 libdispatch.dylib              0x3f88 _dispatch_client_callout
13 libdispatch.dylib              0x7418 _dispatch_continuation_pop
14 libdispatch.dylib              0x6a80 _dispatch_async_redirect_invoke
15 libdispatch.dylib              0x15a6c _dispatch_root_queue_drain
16 libdispatch.dylib              0x16284 _dispatch_worker_thread2
17 libsystem_pthread.dylib        0xdbc _pthread_wqthread
18 libsystem_pthread.dylib        0xb98 start_wqthread
```

For me, it is occurring on the current latest SDK v28.1.0.

**Comment by zvjerka24** [comment]
Last week updated to v28.3.2, and still having users with this crash
