### ISSUE TITLE
Can't cancel out of Onfido flow

### ISSUE THREAD

**Issue by lmmenge** [onfido/onfido-ios-sdk#300]
### What was the expected behaviour?

- Once flow is started, the user should be able to back out/cancel the flow.

### What happened instead?

- Tapping the back arrow does nothing.
- Completion handler for the flow is also not called.

![Simulator Screen Shot - iPhone SE (1st generation) - 2022-06-23 at 09 33 56](https://user-images.githubusercontent.com/51199/175242655-b896a017-ecf2-4f7f-a7c8-3324163b1609.png)

### Version info:

- Cocoapods (if applicable): No Cocoapods. XCFramework used.
- Onfido SDK (Debug/Release): 25.1.0 (Release)
- iOS: 15.5
- Xcode: 13.4
- Device/Simulator: Simulator
- Device/Simulator language: English/USA

### Integration configuration:

```
	ONFlowConfigBuilder* configBuilder = [ONFlowConfig builder];
	[configBuilder withSdkToken:@"valid token here" expireHandler:^(void (^ handler)(NSString *  expireHandler))
	 {
		// Token refresh code here
	}];
	
	Builder* faceVariantBuilder = [ONFaceStepVariantConfig builder];
	[faceVariantBuilder withVideoCaptureWithConfig:NULL];
	ONFaceStepVariantConfig* variantConfig = [faceVariantBuilder buildAndReturnError:&configError];
	
	// variantConfig error handling here
	
	[configBuilder withFaceStepOfVariant:variantConfig];
	[configBuilder withCustomLocalizationWithTableName:@"Onfido"];

	NSError* documentVariantError = nil;
	ONDocumentTypeVariantConfig* documentVariantConfig = nil;
	DocumentConfigBuilder* documentVariantBuilder = [ONDocumentTypeVariantConfig builder];
	[documentVariantBuilder withNationalIdentityCardWithConfig:[[NationalIdentityConfiguration alloc] initWithDocumentFormat:DocumentFormatCard country:@"NLD"]];
	documentVariantConfig = [documentVariantBuilder buildAndReturnError:&documentVariantError];
	
	// documentVariantConfig error handling here

	if(documentVariantConfig != nil)
	{
		[configBuilder withDocumentStepOfType:documentVariantConfig];
	}
	
	ONFlowConfig* config = [configBuilder buildAndReturnError:&configError];
	if(configError == NULL)
	{
		ONFlow* onFlow = [[ONFlow alloc] initWithFlowConfiguration:config];
		// Flow continues...
	}
```

### Steps to reproduce:

Just start the flow and try to cancel out of it on the first screen by tapping the back arrow.

**Comment by limnash-onfido** [comment]
Hi @lmmenge , would you be able to provide a screen recording of the same happening? And also if possible, steps to reproduce?

**Comment by limnash-onfido** [comment]
Hello @lmmenge , this issue has been fixed and will be added in our next release. Thank you!

**Comment by lmmenge** [comment]
@limnash-onfido I've tested this on [25.2.0](https://github.com/onfido/onfido-ios-sdk/releases/tag/25.2.0) and it's not fixed:

https://user-images.githubusercontent.com/51199/187650347-b4b0de84-9ecd-4865-ba0b-0485baae185b.mp4

**Comment by limnash-onfido** [comment]
Hi @lmmenge , thanks for reporting. Our Dev Team has been made aware of the same.
