### ISSUE TITLE
Umbrella header missing for version 27.0.0 and upward (27.4.0)

### ISSUE THREAD

**Issue by iCappsCedric** [onfido/onfido-ios-sdk#333]
What was the expected behaviour?
We updated our Onfido SDK via the Swift Package manager to the new 27.0.0 version. We expected it to compile at building.

What happened instead?
The Onfido SDK gave back the following:
Umbrella header for module 'Onfido' does not include header 'ONFComponentContainerInternal.h'

^
:0: error: could not build Objective-C module 'Onfido'

Version info:
Cocoapods (if applicable): /
Onfido SDK (Debug/Release): 27.0.0
iOS: /
Xcode: Xcode 14.1
Device/Simulator: Simulator
Device/Simulator language: English
How to recreate:
Go to Xcode builds settings > Swift compiler - warning policies > treat warnings as error: YES

If I turn this off, it does compile, but it is something that should not be turned off. Please fix it, so it compiles with it on.

**Comment by iCappsCedric** [comment]
there have been 4 new releases, and nobody decided to take this issue into account on the onfido side? Still does not compile unless I turn this off, which should not happen. No other framework we use has this issue.

**Comment by egarni** [comment]
I have the same issue.. Stuck with version 26.1.1

**Comment by vguerci** [comment]
Hello and sorry for the late reply.

We will investigate into this soon, meanwhile, @egarni, as @iCappsCedric reported, you can ignore these warnings as they aren't critical.

**Comment by egarni** [comment]
Still an issue in version "28.0.0"
Like @iCappsCedric we have "treat warnings as error: YES", we have a no warnings policy in our dev team. We don't want to allow warnings because of one dependency.
Let us know when this is fixed.

**Comment by gurpreet-onfido** [comment]
Hello there!

This is to inform you all that we have found a fix for this issue and it should land in next version.

We will keep you posted.

Kind regards
Gurpreet Singh

**Comment by gurpreet-onfido** [comment]
Hello there!

Greetings for the day!

This is to update you that the reported issue has now resolved in our SDK release [28.2.0](https://github.com/onfido/onfido-ios-sdk/releases/tag/28.2.0).

You are requested to upgrade to the latest SDK release and let us know how it goes.

Kind regards
Gurpreet Singh

**Comment by egarni** [comment]
Hello, the warning from `28.1.0` disappeared, but new ones showed up in `28.2.0`
![Screenshot 2023-03-31 at 09 41 13](https://user-images.githubusercontent.com/1777312/229056762-534c858a-6077-44b5-ba04-c965cb12420a.png)

**Comment by iCappsCedric** [comment]
@gurpreet-onfido this is not closed, since there are still umbrella headers missing for your latest version. See above.
This clearly means that they did not turn `treat warnings as error: YES` on while doing this fix.

**Comment by vguerci** [comment]
@egarni, @iCappsCedric, Upgrading from Swift 4.2 to Swift 5.0 solves these warnings on my end, which Swift version are you using, is this something you can consider doing and does it fix the issue for you as well?

**Comment by egarni** [comment]
We're using Swift 5.7

**Comment by iCappsCedric** [comment]
We are using Apple Swift version 5.7.2
I updated to 28.2 and the errors are gone on our side, I am indeed not having the same issue as @egarni , with `treat warnings as error: YES` 🤷

**Comment by iCappsCedric** [comment]
Never mind, i changed the target of app to the DEBUG version, and all above errors still appear, although its Swift 5.7.2

![Uploading Screenshot 2023-03-31 at 14.59.53.png…]()

**Comment by davidgdoll** [comment]
Hello, I'm having the same issue after trying to update to the latest release version. 
Same headers missing and we can't disable warnings as well.
Any news? Thanks!

**Comment by gurpreet-onfido** [comment]
Hello all,

Greetings for the day!

We have released a new version of our SDK [29.2.0](https://github.com/onfido/onfido-ios-sdk/releases/tag/29.2.0) that would resolve this issue. 

Could you please upgrade to latest version [29.2.1](https://github.com/onfido/onfido-ios-sdk/releases/tag/29.2.1) and let us know if the issue still persists. 

Kind regards
Gurpreet Singh

**Comment by davidgdoll** [comment]
Hello @gurpreet-onfido,
Unfortunately I'm still getting one of the errors on Onfido.h using version 29.2.0:
`Umbrella header for module 'Onfido' does not include header 'OpenPACEInteropStructure.h'`

**Comment by egarni** [comment]
Exact same issue as @davidgdoll `Umbrella header for module 'Onfido' does not include header 'OpenPACEInteropStructure.h' with the latest version `Onfido 29.3.0`
<img width="436" alt="Screenshot 2023-08-14 at 08 24 47" src="https://github.com/onfido/onfido-ios-sdk/assets/1777312/de2d924e-0ae0-4521-b1f2-95b97868b36f">
